development: &default
  adapter: postgresql
  encoding: unicode
  database: sqily_development
  pool: 5
  host: <%= ENV["POSTGRES_HOST"].presence || ENV["PGHOST"].presence || "localhost" %>
  username: <%= ENV["POSTGRES_USER"].presence || ENV["PGUSER"].presence || ENV["USER"].presence || "postgres" %>
  password: <%= ENV["POSTGRES_PASSWORD"].presence || ENV["PGPASSWORD"].presence %>

test:
  <<: *default
  database: sqily_test

# USE DATABASE_URL environment variable for production
